### ISSUE TITLE
Feature:  Working Door addon

### ISSUE THREAD

**Issue by oddrobbia** [Tau-ri-Dev/JSGMod-1.12.2#138]
Hello for some of my building project i wanted to use different type of doors but sadly im not good with little tiles so i want to suggest to add different type of doors from the series or maybe even custom one like the one from the ship x304 and the ancient ships and there was an episode in atlantis where space base had submarine doors sometimes it would be good to have also hangar doors for buildings that have hangar decoration structure vertical and horizonal hangar doors

┆Issue is synchronized with this [Trello card](https://trello.com/c/uuHjHlm8) by [Unito](https://www.unito.io)

**Comment by MineDragonCZ** [comment]
Moving to trelo or discord
