### ISSUE TITLE
Bug: FPS drops

### ISSUE THREAD

**Issue by NagaF7** [Tau-ri-Dev/JSGMod-1.12.2#149]
**Describe the bug**
FPS issues in latest AUNIS updates.
I can't play the latest versions of Aunis because of this. Before these updates I could play with a modpack containing at least 100 mods with a minimum of 60 fps. Whereas today, even with mods increasing the performance of the game like Optifine or BetterFPS or FoamFix, I cannot play beyond 8fps (with only Anuis and the mods to make it work).

**To Reproduce**
You must already have a rather average config ... (Not horrible, just average)
Then after launching the game on a world (whether flat or normal) open the inventory.
This brings me down from 60 to 1fps in the inventory menu. After taking Aunis items from my hotbar the fps are 8 until I drop those items.

**Expected behavior**
Maybe add a button in the "low config" configurations that would lower the item details? (seems to be related to the items anyway)
Otherwise maybe change something so that the mod is faster or less greedy when you have these items...

**Screenshots**
I don't have a screen to show as the concerns are lack of FPS...

**Mod version**
The latest version of Aunis that I can use is : aunis-1.12.2-4.9.2.1-alpha
Or the one above but not really higher.

**Comment by TheRedCreations** [comment]
Version is outdated. Please try with latest Version: Aunis-1.12.2-4.10.0.1

**Comment by MineDragonCZ** [comment]
Agree to TRC... Try it with newest version please

**Comment by NagaF7** [comment]
Already, thank you for your answers.
Then I tried it this morning so. After that I wrote this message. And I had the same thing as with the previous versions. The fps bugs from the moment I open the inventory (I tried with only Aunis, Mekanism and Thermal (+ Optifine and BetterFPS)) by modifying the configurations it doesn't change anything for me at all and I haven't no fps.
It is for this reason that I opened this issue, it is that the current version does not allow me to play...

**Comment by MineDragonCZ** [comment]
> Already, thank you for your answers. Then I tried it this morning so. After that I wrote this message. And I had the same thing as with the previous versions. The fps bugs from the moment I open the inventory (I tried with only Aunis, Mekanism and Thermal (+ Optifine and BetterFPS)) by modifying the configurations it doesn't change anything for me at all and I haven't no fps. It is for this reason that I opened this issue, it is that the current version does not allow me to play...

Is the issue up to date nowadays?

**Comment by NagaF7** [comment]
> > Already, thank you for your answers. Then I tried it this morning so. After that I wrote this message. And I had the same thing as with the previous versions. The fps bugs from the moment I open the inventory (I tried with only Aunis, Mekanism and Thermal (+ Optifine and BetterFPS)) by modifying the configurations it doesn't change anything for me at all and I haven't no fps. It is for this reason that I opened this issue, it is that the current version does not allow me to play...
> 
> Is the issue up to date nowadays?

I tried on the new version and there is still a problem when the items of this mod are present in the inventory interface. Otherwise the fps have increased a bit.

**Comment by MineDragonCZ** [comment]
Can u please send here screenshot of your Minecraft video settings GUI?

**Comment by MineDragonCZ** [comment]
Probably fixed in Dev version
