### ISSUE TITLE
Pegasus Gate Dialing Sound

### ISSUE THREAD

**Issue by Onyx1128** [Tau-ri-Dev/JSGMod-1.12.2#153]
Describe Issue:
When dialing a Pegasus gate, if it gets a incoming wormhole while dialing, the sound doesn't stop.

Steps To Reproduce:
1. Dial Pegasus gate to random address
2. Use another gate to dial Pegasus gate while it's dialing and activate.

┆Issue is synchronized with this [Trello card](https://trello.com/c/KcInjeJK) by [Unito](https://www.unito.io)

**Comment by MineDragonCZ** [comment]
Same on every gate

**Comment by MineDragonCZ** [comment]
Transfering this to #234
