### ISSUE TITLE
Mysterious Page gates sometimes can be dialed once but never again

### ISSUE THREAD

**Issue by TinyDeskEngineer06** [Tau-ri-Dev/JSGMod-1.12.2#175]
Bug Description:
When generating a new stargate via a Mysterious Page, sometimes the address may be dialed once, but not twice or more times. When this happens, the gate the player is dialing from closes when the player attempts to step through the gate, and the player does not get sent to the dialed gate, if it even exists. This seems to be random, or perhaps it is related to how much power is stored in the gate. I have also only seen this happen in Survival, but I have not yet tested it with Creative.

1. Generate new stargate with Mysterious Page and dial address shown
2. If dialing is successful, attempt to walk through gate
3. If gate works as expected, repeat a few times until bug occurs

Expected Behavior:
The gate shouldn't close the way it does, and the player should be able to reach the other side.

Mod Version: 1.12.2-4.10.1.0

┆Issue is synchronized with this [Trello card](https://trello.com/c/GVoaZ316) by [Unito](https://www.unito.io)

**Comment by MR-Spagetty** [comment]
Do you have ae2 installed?

**Comment by TinyDeskEngineer06** [comment]
Nope.

**Comment by MineDragonCZ** [comment]
Also check if u have power in teh gate to keep the gate open.
