### ISSUE TITLE
Feature: More tech from the Stargate franchise

### ISSUE THREAD

**Issue by TrickedOutOnCode** [Tau-ri-Dev/JSGMod-1.12.2#178]
**Describe the solution you'd like**
I'd like to suggest adding more tech from the Stargate franchise. Personally, I'd like to see an Asgard beamer and ZPM's, and potentially some kind of dialing computer like what's seen in SG-1.

**Describe alternatives you've considered**
I am aware of the Stargate Fighters mod which has some of the things I'd like, but it feels very incomplete and the Beamer is janky at best. I don't believe a player should have to carry a tracker with them to be used. Some way of using a beamer with OpenComputers/ComputerCraft would be great, also possibly with the universe dialer? Potentially a way of quickly getting around a large base.

┆Issue is synchronized with this [Trello card](https://trello.com/c/kIJQitaj) by [Unito](https://www.unito.io)

**Comment by MineDragonCZ** [comment]
Moving to internal trello site or discord
