### ISSUE TITLE
Bug: White screen from rings stays if teleported to another dimension while screen is white

### ISSUE THREAD

**Issue by uncoveredkhan09** [Tau-ri-Dev/JSGMod-1.12.2#180]
If a player teleports to another dimension (due to commands or other mods such as RFtools) while the screen is white from using the transporter rings, the white screen stays

the player also teleports the same relative distance they were going to travel due to the rings after the teleport, if they hadn't before

the only way to fix this problem is by using the teleporter rings again which is very hard to do unless you have another player helping you get in position since you cant see anything

relogging and dying do not fix this issues either

(ignore the error messages on the top right, they're from another mod related to testing if death would fix it and started long after i got the white screen bug)

┆Issue is synchronized with this [Trello card](https://trello.com/c/vASK4TUG) by [Unito](https://www.unito.io)

**Comment by MineDragonCZ** [comment]
Its probably because of the transport proccess was not finished, so .... How to fix this:

- go inside the rings and do 1 teleportation with them... Then it should be fine.

**Comment by MR-Spagetty** [comment]
possible solution would be to change the blinding white to maybe be a potion effect that lasts however long the whiteness is supposed to be there that way once teh effect runs out teh blinding white must go away
