### ISSUE TITLE
Feature: Invulnerability period after going through stargate

### ISSUE THREAD

**Issue by TinyDeskEngineer06** [Tau-ri-Dev/JSGMod-1.12.2#184]
**Description**
When a server running JSG lags, it can cause players to die after reaching the other side of a stargate. (Possibly the server thinks the player has reentered the receiving gate?) This can be a very big problem on lower-end servers.

**Solution**
Give players a short period of invulnerability after going through a gate, as this would prevent players from dying because of server-side lag.

**Comment by TheRedCreations** [comment]
You could deactivate the killing from wrong side:
![grafik](https://user-images.githubusercontent.com/35812887/187979078-135c3b47-3d4a-419f-8af9-fb1f3a865f06.png)
Line 107

**Comment by TinyDeskEngineer06** [comment]
> You could deactivate the killing from wrong side: ![grafik](https://user-images.githubusercontent.com/35812887/187979078-135c3b47-3d4a-419f-8af9-fb1f3a865f06.png) Line 107

Yeah, I understand that, but I'd prefer keeping it enabled.
