### ISSUE TITLE
Iris events missing from official JSGMod wiki

### ISSUE THREAD

**Issue by TinyDeskEngineer06** [Tau-ri-Dev/JSGMod-1.12.2#185]
The signals sent when an iris or shield changes state (`stargate_iris_opening`, `stargate_iris_closing`, etc.) are not mentioned on the official wiki for JSGMod. It seems like a few more things might also be missing from the wiki's documentation of the OpenComputers integrations.

**Comment by SGUDestiny** [comment]
A lot of things are still missing on wiki, its WIP after all
I suppose wiki writer will fix this issue
By the way, this is wrong place to report issues about wikipedia, there is whole dedicated channel on Discord server for this

**Comment by MR-Spagetty** [comment]
I never encountered any signals to do with the iris/shield thus did not know they existed thus did not document it

I also need to redo the rings OC integration documentation due to the change in the way they worked to acomidate the new address system

**Comment by MineDragonCZ** [comment]
Next week i will probably look on our wiki and (i hope) redo the whole OC integration part.

**Comment by MR-Spagetty** [comment]
Well i have infact added these signals

**Comment by MineDragonCZ** [comment]
> Well i have infact added these signals

Ok, thx
