### ISSUE TITLE
Bug: Version 4.10.1.1 Breaks/Force-Disables Optifine

### ISSUE THREAD

**Issue by Renno231** [Tau-ri-Dev/JSGMod-1.12.2#189]
**Describe the bug**
After updating to the latest version, Optifine is either broken or disabled. Due to this, my average FPS drops from 150 to 40. When reverting back or deleting the mod, Optifine works again.

**Expected behavior**
Optifine should not be disabled by JSG.

**Additional context**
I have created a small modpack to test this and can confirm that Optifine, and potentially other graphical performance-related mods are broken/disabled.

**Comment by Renno231** [comment]
Further testing indicates that the new main menu screen is the culprit of the compatibility issues with Optifine.

**Comment by MineDragonCZ** [comment]
JSG doesnt disable optifine except buttons in main menu

**Comment by Renno231** [comment]
Yes you seem to be right that it hides Optifines visually. I don't know what other mod could be causing it as this is the only significant mod that was updated on the RACraft 12 modpack earlier today. Pre-update, 120+ FPS, post, 30-60 FPS.

**Comment by Renno231** [comment]
Further testing confirms that it is still active despite not being shown with the JSG main menu enabled. However, I have since tested the game without Optifine and the FPS drop continues to persist.
