### ISSUE TITLE
Feature: sg.sendMessage()

### ISSUE THREAD

**Issue by lukasz4444** [Tau-ri-Dev/JSGMod-1.12.2#192]
**Is your feature request related to a problem? Please describe.**
You cannot send data through stargate, by data i mean something else than iris codes.

**Describe the solution you'd like**
Add this function to mod and allow to sending things like messages or files for example **through StarGate.**

**Describe alternatives you've considered**
i don't know is there any alternatives to this function.

**Comment by MR-Spagetty** [comment]
You can send data through the gate other rhan an iris code using the oc modem component (wireless network card) as the gate relays modem messages through it to the other side

**Comment by lukasz4444** [comment]
> You can send data through the gate other rhan an iris code using the oc modem component (wireless network card) as the gate relays modem messages through it to the other side

Yes that's True but you Can't send anything twice in a row.

**Comment by MR-Spagetty** [comment]
Wdym you cant send anything twice in a row

**Comment by lukasz4444** [comment]
> Wdym you cant send anything twice in a row

Sorry, I meant that iris code have to be sent before send message and which can make sending files and data a bit trouble.

Forget what I wrote earlier.
