### ISSUE TITLE
Feature: Manual Iris Control

### ISSUE THREAD

**Issue by lukasz4444** [Tau-ri-Dev/JSGMod-1.12.2#193]
**Is your feature request related to a problem? Please describe.**
No one has really time to come to the directly stargate and close the iris in gui. 

**Describe the solution you'd like**
Add new block that when clicked closes the iris on linked stargate.

**Describe alternatives you've considered**
Redstone input for stargate base block that when given redstone signal toggles the iris.

**Additional context**
And i know there exists option to do that by computer but if you have power malfunction then good luck.

**Comment by MineDragonCZ** [comment]
You can use OC to control iris
