### ISSUE TITLE
Bug: Duplicate Stat ID Server crash

### ISSUE THREAD

**Issue by MetaverseRPN** [Tau-ri-Dev/JSGMod-1.12.2#198]
**Describe the bug**
When starting up my server with JSG server 4.10.1.1, the server is crashing on boot with a Duplicate stat ID exception
**To Reproduce**
1. Launch server with JSG server 4.10.1.1
3. Wait for server to start up
4. See crash

**Expected behavior**
Server should start up withing crashing before finishing start up
**Screenshots**

**Mod version**
Version of mod you are using. (aunis-1.12.2-4.9.4.3) JSG-4.10.1.1-server

**Additional context**
Crash log Is attached below: 
[crash-2022-11-18_22.48.34-server.txt](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/10047572/crash-2022-11-18_22.48.34-server.txt)

**Comment by TheRedCreations** [comment]
Aunis and JSG are SAME MOD!!!
Delete one of them and you are fine

**Comment by MetaverseRPN** [comment]
Huh. I thought I had removed it. Seems it didn't get deleted when I was cleaning out the outdated mods via FTP. Sorry for wasting your time here.

**Comment by TheRedCreations** [comment]
> Huh. I thought I had removed it. Seems it didn't get deleted when I was cleaning out the outdated mods via FTP. Sorry for wasting your time here.

No worries. We are here to help :)
