### ISSUE TITLE
Adding a stargate holder.

### ISSUE THREAD

**Issue by AntohaKapitoha** [Tau-ri-Dev/JSGMod-1.12.2#200]
When connecting the gate to a computer system or power from other mods, the wiring has to be brought to the core of the gate. Which causes the creation of technical holes in the floor for the supply of cables.
Is it possible to create holders for gates like in Stargate SG-1, to which wiring could be connected anywhere?

**Comment by Fredyman95** [comment]
Possibility tl connect energy cables is already in game - several versions back.

About connection to computer - computer must be connected to main block of stargate - thats a base block.

Also clamps are planned with platforms...

**Comment by AntohaKapitoha** [comment]
I meant that the holders themselves will be like a universal conductor unit, to which power and control can be brought anywhere to hide the wiring.

**Comment by Fredyman95** [comment]
Send me your discord name. Also energy can be connected on EVERY STARGATE BLOCK! Computer connection cant be done like that, becuase only 1 block control, set, define...  stargate and thats the base bloxk

**Comment by Fredyman95** [comment]
Also if you use mod e.g enderIO thats have OC conduits and energy conduits you can make it in one block + cover it

**Comment by AntohaKapitoha** [comment]
Бражник#2918 discord
