### ISSUE TITLE
Slightly incorrect operation of the beam transmitters.

### ISSUE THREAD

**Issue by AntohaKapitoha** [Tau-ri-Dev/JSGMod-1.12.2#201]
When using beam transmitters in one dimension, everything works, energy, liquids and objects move, but if the Stargate is in different dimensions, communication between the transmitters is not established. I do not know if they work correctly and whether they should establish a connection at all.

**Comment by MR-Spagetty** [comment]
Have you made sure that they are aligned correctly as in all current versions if the beamer is misaligned it will not connect

**Comment by MineDragonCZ** [comment]
Closing because of new system of beamers
