### ISSUE TITLE
Bug: my minecraft shuts down when i open it. im on a laptop. ive updated my driver(it says bad video drivers). ive even updated my computer. ive restarted and everything and it doesnt work

### ISSUE THREAD

**Issue by Justaperson12** [Tau-ri-Dev/JSGMod-1.12.2#208]
[crash-2023-01-07_20.43.18-client.txt](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/10366356/crash-2023-01-07_20.43.18-client.txt)

**Comment by Fredyman95** [comment]
I dont want to be mean. But you already asked on discord. Game litteraly tells you that you have bad video drivers. - Its problem on your side and we can't solve it, because its not a bug of mod, but problem with you computer.

**Comment by Justaperson12** [comment]
oh ok

**Comment by Justaperson12** [comment]
> I dont want to be mean. But you already asked on discord. Game litteraly tells you that you have bad video drivers. - Its problem on your side and we can't solve it, because its not a bug of mod, but problem with your computer.

but how do i get my "bad" video drivers good?

**Comment by Fredyman95** [comment]
> > I dont want to be mean. But you already asked on discord. Game litteraly tells you that you have bad video drivers. - Its problem on your side and we can't solve it, because its not a bug of mod, but problem with your computer.
> 
> but how do i get my "bad" video drivers good?

Did you know google.com? If you write here minecraft bad video cards driver. I bet that in top 5 will be solution of this issue


https://www.google.com/search?q=minecraft+bad+video+card+drivers&oq=minecraft+bad+video+&aqs=chrome.2.69i57j69i61j0i512l2j0i22i30l6.6126j0j4&client=ms-android-samsung-ss&sourceid=chrome-mobile&ie=UTF-8

**Comment by Justaperson12** [comment]
> > > I dont want to be mean. But you already asked on discord. Game litteraly tells you that you have bad video drivers. - Its problem on your side and we can't solve it, because its not a bug of mod, but problem with your computer.
> > 
> > 
> > but how do i get my "bad" video drivers good?
> 
> Did you know google.com? If you write here minecraft bad video cards driver. I bet that in top 5 will be solution of this issue
> 
> https://www.google.com/search?q=minecraft+bad+video+card+drivers&oq=minecraft+bad+video+&aqs=chrome.2.69i57j69i61j0i512l2j0i22i30l6.6126j0j4&client=ms-android-samsung-ss&sourceid=chrome-mobile&ie=UTF-8

thats what i did. do you think id come bangin on your face if i had not done that already. come on

**Comment by MineDragonCZ** [comment]
Minecraft 1.12.2 requires OpenGL 1.1 at minimum... If your GPU doesnt support GL 1.1, when it can be solven only by one way: Buy new GPU that supports GL 1.1.

Have a nice day.

**Comment by MineDragonCZ** [comment]
Update to 4.10.1.1
