### ISSUE TITLE
Problem with StructureGenerator RAM usage

### ISSUE THREAD

**Issue by craft90** [Tau-ri-Dev/JSGMod-1.12.2#211]
**Describe the bug**
The Tokra structure has caused my game to crash three times. I have tried to up the RAM allocation to combat it. 

**To Reproduce**
It happens when the Tokra structure attempts to randomly spawn. It causes lag and then crashes.

**Mod version**
jsg 1.12.2 - 4.11.0.1

**Additional context**
Crash log https://pastebin.com/s2rKaSgA

**Comment by MineDragonCZ** [comment]
Out of memory... Allocate more RAM.

**Comment by craft90** [comment]
This crash happened when I had 10GB of RAM allocated. I only have 16GB of RAM installed. If I allocate more then my entire system may become unstable. It only happens when the game generate the Tokra structure.

**Comment by craft90** [comment]
Things seems more stable at 12GB, which is the maximum CurseForge app allows.

**Comment by craft90** [comment]
Addo
I did notice that in and around the Tokra structure I experienced some block lag. The console complained about lagging behind by x ms. When moving away the server calmed down.

**Comment by FamousL** [comment]
Might need to reopen this issue, each time a new tr_tokra structure generates it kicks off the players on my server.  Server remains running, and players can rejoin, however timeout occurs and they are booted.
