### ISSUE TITLE
Bug: Inconsistencies with Crafting Reciepes

### ISSUE THREAD

**Issue by SerinaLikesBugs** [Tau-ri-Dev/JSGMod-1.12.2#216]
**Describe the bug**
Titanium dust requres JSG specific dust not general dustTitanium, You also can't crush the Raw titanium ore into dust in a pulverizer like you can trinium

**Expected behavior**
Preferably for the materials to all be craftable in similar manners.

**Mod version**
4.11.0.2

┆Issue is synchronized with this [Trello card](https://trello.com/c/dlSvJCQl) by [Unito](https://www.unito.io)

**Comment by MineDragonCZ** [comment]
I can't delete crafting recipe with machines from other mods.
