### ISSUE TITLE
Bug: Gate heat red color OpenGL error

### ISSUE THREAD

**Issue by IronmanVeronika** [Tau-ri-Dev/JSGMod-1.12.2#217]
Version 4.11.0.2 
on mw and peg gate only the inner ring and the first chevron glow when heated up and on uni gate the ring and the first chevron glow

**To Reproduce**
1. heat up gate with laser beamer
2. wait
3. wait until u see that some parts are red and others are not

![2023-01-23_22 18 18](https://user-images.githubusercontent.com/95937481/214641531-bcb9db16-e8d2-4b51-9d55-e0750189edae.png)
![2023-01-23_22 21 27](https://user-images.githubusercontent.com/95937481/214641572-eeb45ebd-c670-4c29-9ade-ec45a5abd858.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/XNs2Uvms) by [Unito](https://www.unito.io)

**Comment by MineDragonCZ** [comment]
Try to disable shaders

**Comment by IronmanVeronika** [comment]
The shader doesnt change anything. its the same with and without it. its an error with the textures

**Comment by MineDragonCZ** [comment]
Strange

**Comment by IronmanVeronika** [comment]
You cant get the same result??? Very strange. maybe this is the reason: i changed the maximum gate temperature (i think it was 1/10). then i tested it and got this result. then i changed it back to the default and restarted mc. then i tested again and got  the same result again. maybe it was the change in the config? i dont know

**Comment by MineDragonCZ** [comment]
Yeah, can be. What temperature tha gate had when this happened?

**Comment by IronmanVeronika** [comment]
it is at every temperature between when it heats up until it explodes. so 500 - infinite

**Comment by weberlepecheur** [comment]
I was able to reproduce it, don't know where it comes from though. Will try to reproduce it with minimum requirements.
And like said before, with or not shader. It's still the same, maybe optifine ?

version: jsg-1.12.2-4.11.0.3-client
[modlist.txt](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/10549146/modlist.txt)
![2023-01-31_18 14 33](https://user-images.githubusercontent.com/18701493/215836899-5c69e409-90bd-4804-bed3-9f1bbc4f8c39.jpg)

**Comment by MineDragonCZ** [comment]
It's probably OpneGL problem with coloring the model
