### ISSUE TITLE
Crash: Crash while on main menu.

### ISSUE THREAD

**Issue by weberlepecheur** [Tau-ri-Dev/JSGMod-1.12.2#219]
**Describe the bug**
After playing in my singleplayer world, I came back to main menu to change world but just sat in the main menu while I go in the toilet, when I came back minecraft crashed.

[crash-2023-01-30_17.23.41-client.txt](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/10537827/crash-2023-01-30_17.23.41-client.txt)

**Screenshots**
![image](https://user-images.githubusercontent.com/18701493/215536895-84715f32-b922-4a9c-a6c2-5418dd6ed5c1.png)

**Mod version**
jsg-1.12.2-4.11.0.3-client

┆Issue is synchronized with this [Trello card](https://trello.com/c/EjNZeF5Z) by [Unito](https://www.unito.io)

**Comment by MineDragonCZ** [comment]
Yeah, i know about that, but for now it's random and I don't know what is causing it.

**Comment by MineDragonCZ** [comment]
Should be fixed because of sound preloading system
