### ISSUE TITLE
Bug: ZPM capacity hardcap

### ISSUE THREAD

**Issue by Sarous** [Tau-ri-Dev/JSGMod-1.12.2#222]
**Describe the bug**
ZPM capacity defaults to 0.

/give @s jsg:zpm 1 0 {longEnergy:*}
Using a value * greater than 2000000 produces an item with a NBT tag/energy capacity of 0. Values of 2000000 or lower have the expected capacity. This behavior is also experienced when writing crafting recipes via CraftTweaker.

4.11.05

Edit: Further testing, the exact number is {longEnergy:2147483647}

**Comment by MineDragonCZ** [comment]
Put "L" behind the number. E.g: `/give @s jsg:zpm 1 0 {"longEnergy":4000000000000L}`
