### ISSUE TITLE
Feature: IC2 Recipe compatibility

### ISSUE THREAD

**Issue by Sarous** [Tau-ri-Dev/JSGMod-1.12.2#223]
Request: Full compatibility with IC2 as a functional tech mod, as an alternate option to TE.

<details>
<summary>I have taken the liberty of composing a script using IC2 machines. This script was written for, and works with, IndustrialCraft 2 v.2.8.222 ex112, CraftTweaker v.4.1.20.683, IC2Tweaker v.0.2.1 build 4, Just Stargate Mod v.4.11.0.5. File may be named anything, but requires an extension of ".zs" and to be located at "../minecraft/scripts/"</summary>
recipes.addShapeless(<jsg:naquadah_dust>*2,[<jsg:naquadah_raw_dust>,<ic2:dust:8>]);
mods.ic2.Compressor.addRecipe(<jsg:crystal_fragment>, <minecraft:quartz_block>);
mods.ic2.OreWasher.addRecipe([<jsg:titanium_purified>, <jsg:titanium_nugget>*2], <jsg:titanium_impure>);
mods.ic2.OreWasher.addRecipe([<jsg:naquadah_purified>, <jsg:naquadah_nugget>*2], <jsg:naquadah_impure>);
mods.ic2.OreWasher.addRecipe([<jsg:titanium_purified>, <jsg:trinium_nugget>*2], <jsg:trinium_impure>);
mods.ic2.ThermalCentrifuge.addRecipe([<ic2:dust:13>], <minecraft:sand>*20, 500);
mods.ic2.ThermalCentrifuge.addRecipe([<jsg:titanium_raw>, <jsg:trinium_nugget>], <jsg:titanium_purified>);
mods.ic2.ThermalCentrifuge.addRecipe([<jsg:naquadah_raw>, <jsg:naquadah_nugget>], <jsg:naquadah_purified>);
mods.ic2.ThermalCentrifuge.addRecipe([<jsg:trinium_raw>, <jsg:titanium_nugget>], <jsg:trinium_purified>);
mods.ic2.MetalFormer.addRollingRecipe(<jsg:plate_titanium>, <jsg:titanium_ingot>);
mods.ic2.MetalFormer.addRollingRecipe(<jsg:plate_trinium>, <jsg:trinium_ingot>);
mods.ic2.MetalFormer.addRollingRecipe(<jsg:plate_naquadah>, <jsg:naquadah_alloy>);
mods.ic2.MetalFormer.addRollingRecipe(<jsg:plate_naquadah_raw>, <jsg:naquadah_alloy_raw>);
mods.ic2.Macerator.addRecipe(<jsg:titanium_dust>, <jsg:titanium_ingot>);
mods.ic2.Macerator.addRecipe(<jsg:trinium_dust>, <jsg:trinium_ingot>);
mods.ic2.Macerator.addRecipe(<jsg:naquadah_dust>, <jsg:naquadah_alloy>);
mods.ic2.Macerator.addRecipe(<jsg:naquadah_raw_dust>, <jsg:naquadah_alloy_raw>);
mods.ic2.Canner.addEnrichRecipe(<liquid:silicon_molten_black>*1000, <liquid:water>*1000, <item:ic2:dust:13>);
mods.ic2.Canner.addEnrichRecipe(<liquid:silicon_molten_white>*1000, <liquid:silicon_molten_black>*1000, <item:ic2:dust:13>*4);
mods.ic2.Canner.addEnrichRecipe(<liquid:silicon_molten_red>*1000, <liquid:silicon_molten_black>*1000, <item:minecraft:redstone>*4);
mods.ic2.Canner.addEnrichRecipe(<liquid:silicon_molten_pegasus>*1000, <liquid:silicon_molten_black>*1000, <item:ic2:dust:5>);
mods.ic2.Canner.addEnrichRecipe(<liquid:silicon_molten_yellow>*1000, <liquid:silicon_molten_black>*1000, <item:minecraft:glowstone_dust>*2);
mods.ic2.Canner.addEnrichRecipe(<liquid:silicon_molten_blue>*1000, <liquid:silicon_molten_black>*1000, <item:ic2:dust:9>*4);
mods.ic2.Canner.addEnrichRecipe(<liquid:silicon_molten_ender>*1000, <liquid:silicon_molten_black>*1000, <item:ic2:dust:31>);
</details>

**Comment by MineDragonCZ** [comment]
TE will be only optional dependency when last machine is done. (Ancient Chemical Lab)

**Comment by MineDragonCZ** [comment]
If you want, you can use our https://discord.justsgmod.eu/ where you can post your skript into #addons channel (under comunity section)

**Comment by Sarous** [comment]
Cannot post there due to lack of permissions
