### ISSUE TITLE
Universe Random page error

### ISSUE THREAD

**Issue by DeathToCountry** [Tau-ri-Dev/JSGMod-1.12.2#227]
Use of the Random Universe Generator page, creates Universe dialer, but when dialed will not establish wormhole. Upon connection to Auspex Dialing Program thru OpenComputers, program only shows dialing process then "Stargate is resetting" upon 9th chevron lock. Attempt has been made 8 times.

![2023-02-21_02 52 06](https://user-images.githubusercontent.com/16582184/220310819-8d05abd3-ee71-4266-bdb4-2ce8cab8846a.png)

![2023-02-21_02 55 09](https://user-images.githubusercontent.com/16582184/220311282-a9b77234-a5fc-40eb-9d9e-b25e5d10a858.png)

![2023-02-21_02 55 10](https://user-images.githubusercontent.com/16582184/220311305-94f8fe7f-9bb1-4e98-8c50-3b28631e63d9.png)

**Comment by MineDragonCZ** [comment]
Probably not enough power

**Comment by DeathToCountry** [comment]
Zpm hooked up to Tauri hub, full charge both on zpm and gate

**Comment by DeathToCountry** [comment]
I've also noticed, and this is possibly the cause, Universe gates across dimensions will not connect. Only Milky Way/Lantean gates will connect to Uni gates across dimensions and vice versa

**Comment by MineDragonCZ** [comment]
As I wrote... Not anough power to open wormhole to other dim with Uni gate without capacitors.
