### ISSUE TITLE
Bug: Zpm hub not draining zpms 

### ISSUE THREAD

**Issue by FamousL** [Tau-ri-Dev/JSGMod-1.12.2#231]
**Describe the bug**
Zpm hub not draining zpms while powering other devices

**To Reproduce**
Place zpm hub
Connect to devices of choice using mekanism cables
insert zpms
???
Profit

**Expected behavior**
Zpms should drain energy

**Screenshots**
![image](https://user-images.githubusercontent.com/27971720/221199625-24d523a5-e921-41de-bebe-899579eadbb4.png)

**Mod version**
jsg-1.12.2-4.11.0.5-client.jar

**Additional context**

**Comment by DeathToCountry** [comment]
I had the same issue when the update came out. Any old zpms began doing this, but new zpms followed program perfectly

**Comment by FamousL** [comment]
Confirmed on my end, zpms pictured are of the elder variety, newer zpms do not exhibit this behavior.

**Comment by MineDragonCZ** [comment]
Thanks, closing...
