### ISSUE TITLE
Bug: ring platform coordinate lag spike

### ISSUE THREAD

**Issue by FamousL** [Tau-ri-Dev/JSGMod-1.12.2#232]
**Describe the bug**
When placing a ring platform at coordinates over 20k, there is a considerable difference in how long it takes the server to process the placement when compared to placing the ring platform at lower coordinate values. 

**To Reproduce**
Expand range to max (as defined by the config file)
Place platform at 0,~,0 (notice lag as it does it's thing)
Place second platform at 23635 ~ 3057 (compare difference in processing time)

**Expected behavior**
While the expanded area should cause more delay, I wouldn't expect the position of the rings to impact how bad that delay gets.

**Mod version**
jsg-1.12.2-4.11.0.5-client

**Comment by MineDragonCZ** [comment]
Just don't set the range to maximum...

**Comment by FamousL** [comment]
Still occurs at 20X20 range, just less so.
