### ISSUE TITLE
Bug: Titanium Gears and GDOs. (Ore Dictionary issue)

### ISSUE THREAD

**Issue by Stargate4Life** [Tau-ri-Dev/JSGMod-1.12.2#236]
I am playing in a modpack, All The Mods 3, and added this mod to it obviously. It works nicely and I am really enjoying this mod btw, thank you for making it but I hit a snag. While trying to craft the GDO the titanium gear does not appear to be craftable because the other titanium gears override it, due to Ore Dictionary. The Vulpes titanium gears can be used for some things but not for the GDO.

1. Go to inventory screen
2. Search for the mod in JEI
3. Click on the GDO
4. Hold the shift key on the gear
5. The Ore Dic says gearTitanium but doesnt accept any type of the gear to craft the item

Other things in the mod that use titanium gears however do allow the use of the Vulpes gears, so its set to work on some things but not on that important item and possibly more, I am just not sure as to all of what does and doesn't allow the those gears.

In this screenshot you can see the recipe for the GDO, note the gear doesn't state that any gear is accepted except that one.
![2023-03-09_13 26 53](https://user-images.githubusercontent.com/127440375/224133759-1b4c826e-d7d1-49e6-b1af-b9b17885150c.png)

In this screenshot however you can see the other machines from the mod accepting any titanium gear according to the Ore Dictionary.
![2023-03-09_13 28 40](https://user-images.githubusercontent.com/127440375/224133923-85e9fb5e-694c-43d3-90f8-618b465cd924.png)

I am using jsg-1.12.2-4.11.0.5-client

Additionally I want to caution players, **using the forge lexicon to convert gears or plates will not work and will only crash your game. At the same time changing the ingots over to the ones from the mod doesn't fix the recipe sense the recipe for the gear from JSG simply stops existing**. I hope I was as helpful as possible.

**Comment by MineDragonCZ** [comment]
Thats a modpack problem. Its not possible to make mod compatible with all other mods...

Sorry, but i think I can't help you with that.
However, thank you for playing mc with JSG.

**Comment by Stargate4Life** [comment]
I see. Well, I guess thank you. I think it could be possible, as there are 200 something mods in this pack almost all of which have their own independent recipes and accepted items that interchange in the Ore Dictionary. This is quite literally the first conflict I have ever seen with it and at the same time will serve as a problem for those, like myself, that wish to use it in modpacks. Modpacks that add in the same metals and gears and other things. I am not arguing with you, I don't code so I don't know what the process would be to make a thing possible, but I do think it will remain an issue that causes issues for many people wishing to use this mod as it takes away from the immersion having to cheat in the item. Not everyone playing the game or running a server will know how to fine tune every small detail.

**Comment by Fredyman95** [comment]
Well like Minedragon wrote you. This conflict is caused by mod conflicts. It can be easily solved by MODPACK developer - change recipe for this gear or change recipe for GDO with another mod e.g. crafttweaker II...

Thats why is not possible to make mod compatible with all mods... somebody use oredictionary gearTitanium, but other use titaniumGear ... basicly same item but 2 different oredict names... and in this situation modpack developer need to adjust recipes or mechanics only inside modpack...

**Comment by Stargate4Life** [comment]
Thank you for giving more information on it, I am still learning the way oredic works but was very annoyed yesterday about the recipe. I don't know if it would retain the recipe if I add the mod into a modpack I was constructing, mostly because I also don't know how crafttweaker works either. I added a thing at the end of my report, the recipe disappears and forge lexicon won't convert the items. the recipe probably vanished for a number of reasons but I have to warn people not to use the lexicon from the Thermal Series because it will crash the game and delete the item.

**Comment by MineDragonCZ** [comment]
> Thats a modpack problem. Its not possible to make mod compatible with all other mods...
> 
> Sorry, but i think I can't help you with that. However, thank you for playing mc with JSG.

Maybe it will be fixable :)
