### ISSUE TITLE
Nether Gate refuses to establish connection with orlin gate.

### ISSUE THREAD

**Issue by captinwill** [Tau-ri-Dev/JSGMod-1.12.2#239]
**Describe the bug**
The Nether DHD locks up when I attempt to dial the address of earth and when I get to the fifth chevron.

**To Reproduce**
1. Place a chunkloader that affects the orlin gate
2. Use orlin gate to go to nether
3. attempt to return to orlin gate

**Expected behavior**
I expected to return to orlin gate

**Mod version**
jsg-1.12.2-4.11.0.5

**Additional context**
Is odd and is random when it happens. also had recently beat the end with the End reborn mod

**Comment by Fredyman95** [comment]
How man times did you opened orlins gate?

Orlins gate can be opened (dialing or receiving wormhole) only 2 times by default options.

Also is possible that milky way stargate havent enough energy to establish connection

**Comment by captinwill** [comment]
Orlin gate had one remaining use for RETURN.
Nether gate had way more power than needed.
Also, read the description:
"The Nether DHD locks up when I attempt to dial the address of earth and when I get to the fifth chevron."

**Comment by MineDragonCZ** [comment]
Can you provide log, please?

**Comment by captinwill** [comment]
this was over a month ago i do not have the log anymore. Furthermore, this has not happened again.
