### ISSUE TITLE
Rings remote

### ISSUE THREAD

**Issue by MineDragonCZ** [Tau-ri-Dev/JSGMod-1.12.2#24]
Remote controller for transport rings.

┆Issue is synchronized with this [Trello card](https://trello.com/c/e2bgUQfo) by [Unito](https://www.unito.io)

**Comment by DeathToCountry** [comment]
Doesn't the Uni dialer already have this?

**Comment by MR-Spagetty** [comment]
What is planned here is something like the portable goa'uld ring controller
