### ISSUE TITLE
Crash when getting close to a village 

### ISSUE THREAD

**Issue by ar1810** [Tau-ri-Dev/JSGMod-1.12.2#241]
*Describe the bug*
When i get close to a village the game crashes

*Expected behavior*
Not crash

*Screenshots*
![image](https://user-images.githubusercontent.com/42499535/230252170-0db933e9-f54f-47c7-9191-2a367e18a891.png)

*Mod version*
jsg-1.12.2-4.11.0.5

*Additional context*
[crash-2023-04-05_22.42.38-server.txt](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/11165570/crash-2023-04-05_22.42.38-server.txt)

**Comment by Fredyman95** [comment]
Known bug with rings generation... turn off TR generation in JSG world gen
