### ISSUE TITLE
Feature: Naquadah Generators and Project Arcturus

### ISSUE THREAD

**Issue by Stargate4Life** [Tau-ri-Dev/JSGMod-1.12.2#242]
I don't know if there is a chance if this is planned or if the mod is still being worked on but I was playing and thinking of something that would be good to have in this mod. We can get Naquadah but at the moment nothing to generate power with it, one good idea to absolutely add in if its not already in the works. Another idea that would be really interesting to see is Project Arcturus, a way of creating zero point energy. Even being on point with the show it can be just as difficult to maintain and requiring an enormous amount of power to generate power, to add to the idea it could be a multiblock setup as well. I just wanted to put the ideas out there just to see what everyone thinks.

**Comment by Stargate4Life** [comment]
Oh I should add this, in case some don't know or remember Project Arcturus. https://stargate.fandom.com/wiki/Project_Arcturus I think it could make a great late game power generation source while also being highly dangerous to unstable.

**Comment by MineDragonCZ** [comment]
Moving to internal trello site or discord
