### ISSUE TITLE
Bug: Incoming Wormhole Interruption Bug

### ISSUE THREAD

**Issue by lukasz4444** [Tau-ri-Dev/JSGMod-1.12.2#248]
**Describe the bug**
Incoming Wormhole Bug

**To Reproduce**
1. Dial with from one milkyway stargate to second one
2. just right before first stargate will lock 6 symbol make second gate go to failing state by pressing BRB (or make stargate to be in no lock state [i mean that one when computer have given invalid address to gate]) before animation starts
3. on second gate off world activation will start shortly after that gate will reset
4. first gate will lock the symbol and do fail sound

**Expected behaviour** // misspell :)
Second stargate should refresh and opening the wormhole should work.

**Screenshots**
Nope but here's a quick video showcasing it

https://youtu.be/MPK1jUgnKC8

**Mod version**
**jsg-1.12.2-4.11.0.8-server.jar**

**Additional context**
**Em.... No**

**Comment by MineDragonCZ** [comment]
Its ok. This thing Is here to prevent a bug.
