### ISSUE TITLE
Bug: Crash to desktop on Stargate multiblock change

### ISSUE THREAD

**Issue by jhammerberg** [Tau-ri-Dev/JSGMod-1.12.2#251]
**Describe the bug**
The client or server will crash if an update to the Stargate multi-block is attempted by moving the base block, say with a piston.

**To Reproduce**
1. Form Stargate multi-block
2. Activate a sticky piston on the Stargate base block
3. Crash to desktop
(If you log back into the world then the base block will have been moved but not the rest of the invisible gate blocks, leaving the gate functional but with the invisible ring blocks in the wrong location)

**Expected behavior**
I would expect the multi-block to un-form and only the base move, and of course not crash.

**Mod version**
JSG-1.12.2-4.11.0.8

**Additional context**
I realize the simple fix for this bug would be to make the gate blocks unmovable, and you might want to do that anyway for gameplay reasons, but please consider changing the behavior of the stargate base block to check if the multiblock is complete if it receives a block update. This would fix compatibility with WarpDrive along with resolving this bug (I think). I know you also don't like fixing bugs that aren't strictly with the mod itself but this mod is nearly compatible with WarpDrive and adding the multiblock check would be a simple fix!

**My whole JSG config (as .zip)**
[jsg.zip](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/11713628/jsg.zip)

**Comment by MR-Spagetty** [comment]
Crash log?

**Comment by jhammerberg** [comment]
Right, sorry. You should include that in the bug template
[crash-2023-06-10_21.22.43-server.txt](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/11715300/crash-2023-06-10_21.22.43-server.txt)

**Comment by jhammerberg** [comment]
I am dumb and did not read the crash log. This crash is because Quark allows the movement of tile entities and this breaks a whole bunch of stuff. This is an incompatibility with that quark feature, not the mod.
