### ISSUE TITLE
Bug: Render issue with Ancient Obelisk and Destiny Bearing

### ISSUE THREAD

**Issue by ShicKla** [Tau-ri-Dev/JSGMod-1.12.2#258]
**Describe the bug**
At certain camera angles the Ancient Obelisk and Destiny Bearing will stop rendering

**To Reproduce**
Approach mentioned entities and tilt camera upwards

**Expected behavior**
Constant rendering when entity is in camera field of view. 

**Screenshots**
https://github.com/Tau-ri-Dev/JSGMod-1.12.2/assets/2679084/9c1d6b6e-d709-46f8-9e68-baf32c09fc43

**Mod version**
4.11.1.0-pre3

**Additional context**
Stargates themselfs once had the same issue, I suggest looking at their rendering code for the solution to these entities.

**Comment by MineDragonCZ** [comment]
I can't reproduce it with the Bearing, but with obelisk I can.
