### ISSUE TITLE
Bug: Myst pages gates problem

### ISSUE THREAD

**Issue by IronmanVeronika** [Tau-ri-Dev/JSGMod-1.12.2#260]
immediately shut down when dialing generated gate the first time

1. Make a new gate with mysterious page
2. Dial the Gate
3. Gate activates and closes immediately
4. Active sound still playes although the gate is closed
5. Dial again and everything works normal

**Expected behavior**
Normal dialing and normal opening

**Mod version**
jsg-1.12.2-4.11.1.0-pre4

**My whole JSG config (as .zip)**
normal autogenerated without any changes

**Comment by MineDragonCZ** [comment]
How much power do u have in the gate? Maybe the wormhole just use whole power buffer at once when it opens and thats why the gate closes immediately.

**Comment by IronmanVeronika** [comment]
No, it cant be that. I have 3 Power sources installed, the gates are at normal distance and i tryed it more than once.

**Comment by IronmanVeronika** [comment]
I have made a video now. in this case the problem with the sound doesnt appear. it is only sometimes
https://youtu.be/W6LnIuAtQZQ

**Comment by MineDragonCZ** [comment]
send here log and debug log please

**Comment by IronmanVeronika** [comment]
[2023-07-04-3.log.gz](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/11950953/2023-07-04-3.log.gz)
[debug.log](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/11950954/debug.log)
