### ISSUE TITLE
Bug: stargate.sendMessageToIncoming() not working as it should

### ISSUE THREAD

**Issue by Renno231** [Tau-ri-Dev/JSGMod-1.12.2#264]
**Describe the bug**
The stargate.sendMessageToIncoming() fails to relay information to the incoming stargate.

**To Reproduce**
1. Create event listener for "code_respond" on gate 1
2. Dial from gate 1 to gate 2
3. Close whatever program running on gate 2
4. Try to use stargate.sendMessageToIncoming() (in lua terminal or otherwise)
5. 3rd step returns false, no_listener_available even though there is a listener on gate 1

**Expected behavior**
stargate.sendMessageToIncoming() should send messages to stargates on the otherside of the incoming wormhole, which should be readable via OC api.

**Mod version**
4.11.0.8

**Additional context**
This normally seems to work, but only if the program using the stargate.sendMessageToIncoming is running on the receiving end prior to the wormhole forming.

**My whole JSG config (as .zip)**
[jsg.zip](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/11960936/jsg.zip)

**Comment by Fredyman95** [comment]
Was stargate 1 incoming or outgoing?

**Comment by MineDragonCZ** [comment]
stargate.sendMessageToIncoming() works only when outgoing gate sends iris code to incoming one

**Comment by Renno231** [comment]
For some reason, I didn't get a notification about this. Yes, of course, I know the intended behavior and how this is supposed to work, otherwise, I wouldn't made the post. As you can see by my description of things, Gate 1 is the outgoing side.
