### ISSUE TITLE
Bug: ZPM wont stop discharge

### ISSUE THREAD

**Issue by IronmanVeronika** [Tau-ri-Dev/JSGMod-1.12.2#267]
**Describe the bug**
When ZPM is used to power something it sometimes wont stop discharging even though the thing that consumed the energy is full.

**To Reproduce**
1. load something with zpm
2. wait until its full
3. sometimes the zpm is still discharging

**Expected behavior**
should stop discharge when energy isnt needed anymore

**Screenshots**
https://youtu.be/a8DDfpTrnWs

**Mod version**
jsg-1.12.2-4.11.1.0-pre7

**Additional context**
every beamer in the video was full

**My whole JSG config (as .zip)**
[jsg.zip](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/11969942/jsg.zip)

**Comment by MineDragonCZ** [comment]
What about the other zpm hub?

**Comment by IronmanVeronika** [comment]
its emty

**Comment by TheTerribleT** [comment]
I have had this issue with some types of cables and certain power levels of ZPMs. Putting a fully powered zpm worked fine, but using one I found with the ancient totem it would continuously drain even when only connected to a single cable piece. Probably not relevant or important but something I have noticed.
