### ISSUE TITLE
Bug: Power draw not configuring properly in AR

### ISSUE THREAD

**Issue by TheTerribleT** [Tau-ri-Dev/JSGMod-1.12.2#268]
**Describe the bug**
The power draw configs are not having the desired effects on Advanced Rocketry planets. It could have something to do how the Dims config has DimIDs now?

**To Reproduce**
1. Go to an AR world "Luna/Moon is where I am experiencing it first"
2. Place down a gate. I am using a Universe gate at the moon and dialing a Milky Way in the Overworld.
3. Dial the gate in the Overworld.
4. Watch the Power Draw. It uses very minimal power to open and keep alive.

**Expected behavior**
The power draw should be greatly increased to what it currently is now. The "planet" and "space" options in the Dims Config have a distance of 15.

**Screenshots**
![9 Chevrons](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/assets/32606311/61ef5a2c-ce0a-4cb6-9cea-6943e48b00f1)
![Low Power Draw](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/assets/32606311/4d6ddfa6-1e03-4152-ad8f-8115f7d9d598)

**Mod version**
JSG 4.11.1.0

**My whole JSG config (as .zip)**
[jsg.zip](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/12043537/jsg.zip)

**Comment by MineDragonCZ** [comment]
Just set the distance to higher number (50 for example)

**Comment by TheTerribleT** [comment]
It still persists. I changed Space and Planet to have a distance of 50. The same low power draw is still happening. I tried adding the dim manually in the config but that also had no effect

**Comment by TheTerribleT** [comment]
> It still persists. I changed Space and Planet to have a distance of 50. The same low power draw is still happening. I tried adding the dim manually in the config but that also had no effect

Also when dialing from the space station, it does have a greater power draw and open, however changing the config does not increase or decrease these numbers.

**Comment by Fredyman95** [comment]
1.st thank you for reporting that.
2. If you want to report anything, it will be nice to use default language and font - so latin alphabet and English. - You only make our work harder with that

**Comment by TheTerribleT** [comment]
Will do, sorry
