### ISSUE TITLE
Add two-way travel through Stargate. Just a request.

### ISSUE THREAD

**Issue by masterblaster221** [Tau-ri-Dev/JSGMod-1.12.2#269]
Add two-way travel through Stargate. Just a request.

**Comment by Nexusatko** [comment]
Ignore the non-canon bs sayings and add it, please. :( Config option default false if you want.

**Comment by Fredyman95** [comment]
Sorry, but we are going show accuracy.
+
For suggestions visit our discord server:
[justsgmod.eu/discord](justsgmod.eu/discord)
