### ISSUE TITLE
Requests. (can ignore)

### ISSUE THREAD

**Issue by StargateOPs** [Tau-ri-Dev/JSGMod-1.12.2#270]
I'm not sure if these have been requested before so if have or don't want to do them just ignore this

I'm just wondering is it possible to add black holes into the game for them spawning the rareity of them appearing would be .1 of a chance and they stop your gate from closing while also placing the area in danger of being sucked through a gate if Iris is in place it slowly drains the durability of the physical iris if energy iris then it drains the power at a faster rate then normal like if something was hitting it each second.

if it's possible while traveling you can have the chance of coming across a damaged stargate without a dhd and if you can engage the damaged stargate it would explode cause of the damaged capacitors or damaged parts.

also with the stargate overload is it possible to have a device that can overload the stargate like in the first episode of season six.

**Comment by Fredyman95** [comment]
For suggestions visit our discord server:
justsgmod.eu/discord
