### ISSUE TITLE
Bug: Server crash with Applied Energistics 2

### ISSUE THREAD

**Issue by Nexusatko** [Tau-ri-Dev/JSGMod-1.12.2#275]
**Describe the bug**
 If you generate the gate with the mysterious page there's a 99,99999% chance that there'll be an asteroid which breaks the gate and crashes the server after it tries to close itself or when you try to close it manually.
**To Reproduce**
Described above

**Expected behaviour**
 Not crashing a server?
**Mod version**
 jsg-1.12.2-4.11.1.0
**My whole JSG config (as .zip)**
 Not applicable in this case
Crash report
 https://gist.github.com/Nexusatko/f5ec67522b9f18db1bebcc825f4c2183

**Comment by Bysokar** [comment]
AE2 is famous for its worldgen overriding others. You can mitigate this with AE2 config settings making meteors rarer.

eg:

worldgen {
    **D:meteoriteClusterChance=0.1**
    I:meteoriteDimensionWhitelist <
        0
     >
    **I:meteoriteMaximumSpawnHeight=180**
    **I:minMeteoriteDistance=707**
    I:quartzOresClusterAmount=15
    I:quartzOresPerCluster=4
    D:spawnChargedChance=0.07999998331069946
}
