### ISSUE TITLE
Bug: OC API to get ring type doesn't return ring type

### ISSUE THREAD

**Issue by Renno231** [Tau-ri-Dev/JSGMod-1.12.2#276]
**Describe the bug**
component.transportrings.type shows a static string of "transportrings"

**To Reproduce**
1. Open game, plug computer into JSG rings. Look at component API for the rings.

**Expected behavior**
The API should return the type of rings that the component is.

**Mod version**
Version of mod you are using. (1.12.2-4.11.1.0)

**Comment by MineDragonCZ** [comment]
component.<pheriperal>.type is internal OC getter

method/getter "type" is not in JSG (can be added in future)
