### ISSUE TITLE
Bug: Server side Orlin gate

### ISSUE THREAD

**Issue by IcarusAstralis** [Tau-ri-Dev/JSGMod-1.12.2#280]
**Describe the bug**
On Server i opened the orlin gate and thraveled back throu nether gate but i could stil open the orlin gate three more times and it is still not switching to burned out state.
Or did i get something wrong? The gate was only supposed to work twice travel neather and back right?
I tried relogin on the server but the gate still worked i went to nether and back 7 or 8 times ( Atleast now I know earths address out of my head :D )

**Expected behavior**
Orlin gate only usible 2 times like in config 

**Mod version**
jsg-1.12.2-4.11.1.0

**My whole JSG config (as .zip)**
[server291137_11_Sep_2023_19_46_9.zip](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/12579015/server291137_11_Sep_2023_19_46_9.zip)

**Comment by Fredyman95** [comment]
Is it config from server or from client?

**Comment by IcarusAstralis** [comment]
It is from server--Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 11.09.23, 21:59 schrieb Fredyman95 ***@***.***>:

   
  Is it config from server or from client?

**Comment by MineDragonCZ** [comment]
Any update with new version?

**Comment by IcarusAstralis** [comment]
Trying out may take a while. My computer broke. When it still happens after updating, i will reopen issue.
