### ISSUE TITLE
Bug: ZPM Game Crash

### ISSUE THREAD

**Issue by lukasz4444** [Tau-ri-Dev/JSGMod-1.12.2#281]
**Describe the bug**
Place zpm in survival mode (it can any zpm even from creative) then try to mine it.
You cannot because of the server and client desynchronised, but it is even worse.
Place TNT and activate it next to that glitched placed zpm.
The Server Will crash immediately as soon as the TNT explodes, and any client that it would have this incident in the render distance would also crash.

**I do not mean zpm in the hub but placed in the world**

**To Reproduce**
1. Place any zpm item in the world
2. Place TNT next to it
3. Ignite the TNT
4. Crash the game.

**Expected behavior**
You should be able to mine zpm item if you place it and not crash the game.
TNT should rather erase zpm from existence then crash the server and anybody who sees it.

**Screenshots**

**Mod version**
jsg-1.12.2-4.11.1.0-server

**Additional context**
YOU HAVE TO TRY TO MINE THE ZPM IN SURVIVAL MODE TO HAVE THIS GLITCH TO HAPPEN.

**My whole JSG config (as .zip)**
Upload here your jsg config folder (as .zip) **if it's not default one**

I am using the default one for the server.

**Comment by Fredyman95** [comment]
it's the intention. Explosion of ZPM destroy big area. Note that explosions of JSG blocks/items are WIP - so its not a bug.

**Comment by Fredyman95** [comment]
Its not a bug - feature its not finished yet

**Comment by lukasz4444** [comment]
> Its not a bug - feature its not finished yet

Okay then two questions: 

Why it can't be mined even with silk touch diamond pickaxe (or better tier from mods)?
Why, if the feature is not finished, it isn't disabled?

I am just that type of person that really wants to know everything, so can I please get answers for those two?

**Comment by lukasz4444** [comment]
PS Because it isn't a bug but a unfinished feature i am closing this ticket.

Please answer my questions i am too curious to not know what are the answers.
