### ISSUE TITLE
Bug: Universe gate bugging out

### ISSUE THREAD

**Issue by ConnorVex** [Tau-ri-Dev/JSGMod-1.12.2#282]
**Describe the bug**
When building a Uni gate in the End, it glitches out, resulting in the menu panels freaking out and the gate being unusable by the Uni Dialer

**To Reproduce**
1. Go into the End
2. Build a Universe Gate
3. Try to open the gate Menu
4. Bug appears

**Expected behavior**
The gate to function as intended, allowing me to save the address and dial out

**Screenshots**
Video of the issue:
https://streamable.com/6zqzdx

**Mod version**
jsg-1.12.2-4.11.1.0

**Additional context**
This seems to only occur on a Multiplayer server, as I attempted to reproduce the issue in Singe Player but got 0 results

**My whole JSG config (as .zip)**
[JSG Config.zip](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/12799303/JSG.Config.zip)

**Comment by ConnorVex** [comment]
Updating the Issue:
This doesn't appear to be limited to the Universe Gate, as the Milky Way Gate is also not working inside of the End

**Comment by MineDragonCZ** [comment]
Hi, this bug can be caused by server's lags. Check if the server's TPS are good (ideally 20).

**Comment by ConnorVex** [comment]
Server TPS is stable when the bug happens (Remains on 20 perfectly)

Is there any other way to figure out why this bug is appearing?

**Comment by ConnorVex** [comment]
So after extensive testing with my mods, I figured out the culprit. It is this mod called [Server Pauser](https://www.curseforge.com/minecraft/mc-mods/serverpauser)

I don't know what is going on, but it and JSG are not playing nice together. Removed it and so far my issue has vanished suddenly, will update this issue if it reappears
