### ISSUE TITLE
Bug: Beamers Not Connecting

### ISSUE THREAD

**Issue by Goodbuster98** [Tau-ri-Dev/JSGMod-1.12.2#283]
On my server I was trying to setup the laser Beamer, but I only get the first green dot in its UI. I've tried breaking and replacing the beamer and the gate but I'm still unable to connect get it to connect to the gate to then fire the beam.

I'm using the mod version:  JSG-1.12.2-4.11.1.0

This Is my custom config I'm Using [jsgConfig_3.2.zip](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/13251569/jsgConfig_3.2.zip)

![2023-11-03_14 54 10](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/assets/109917010/4fcfdd5e-4b3c-44c1-8c7f-4507668d6723)
![2023-11-03_14 54 21](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/assets/109917010/2a4f657d-2875-4823-b427-a05f8cc6d58d)
![2023-11-03_14 54 38](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/assets/109917010/b5d0055e-0775-46bf-81fa-6ebe10119cc2)

**Comment by MineDragonCZ** [comment]
The beamer is far away from the gate

**Comment by Goodbuster98** [comment]
I've altered the config so the beamers can be 50 blocks away. The issue is only happening for the laser beamer

**Comment by MineDragonCZ** [comment]
And if u open the gate?

**Comment by Goodbuster98** [comment]
It still stays the same and nothing happens

**Comment by MineDragonCZ** [comment]
For me it's working... Check if you are editing correct config and if yes, then try rebuild the beamer

**Comment by MineDragonCZ** [comment]
![2023-11-03_17 42 36](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/assets/78699120/941358f2-be23-468b-bed6-f07a4c02b670)
![2023-11-03_17 42 44](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/assets/78699120/cce2b5e7-e75a-47b6-98bf-4df223ab3996)

**Comment by Goodbuster98** [comment]
Eventually it's started to work on my single player world but only after deleting my config a few times and redoing it
