### ISSUE TITLE
Bug: unable to break gates wtih "iron pick" after disabling Wrench disassembly option

### ISSUE THREAD

**Issue by Shibva** [Tau-ri-Dev/JSGMod-1.12.2#284]
**Describe the bug**
When I disable the config option for disassembling a wrench with a gate, the iron pickaxe will not allow me to mine the back

**To Reproduce**
should be self-explanatory

**Expected behavior**
It allows me to break with an Iron pickaxe or any pickaxe

**Mod version**
1.12.2-4.11.2.1.

**Additional context**
This might be due to something I made to account for this issue before the update; For context, I, with some help, made a CT script that allows me to break placed gates with any tool while ones generated in the world are unminable unless you are using a specific tool. **It should be noted this was working before the update released on the 4th of November 2023**

**I disabled this script and yet it is still acting up without it**. What I hope is that there is a means to fully disable this security implementation to allow for this script to work again or some form of equivalent to be implemented in the future. If you are curious about what this is and how it works, then use this script here, **Please note that you will need to Install Crafttweaker and in the file change the contents of `allowedTool` to `<minecraft:diamond_pickaxe>` for it to work with just these mods present**
[worldgen_gate_manager V!.zip](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/13258926/worldgen_gate_manager.V.zip)
     (How it works: if you place a gate block/dhd it will set a custom value in the ForgeData parameter inside the matching block when placed; if this value is present, you can break the block with any tool like normal; if it does not (like in worldgen) the gate will be unbreakable unless the tool you're using to mine it matches `allowedTool`. The purpose of this script is to prevent worldgened gates from being "salvaged" until the player reaches a point to acquire specific tools to break wolrdgen gates while ones placed by a player can be broken like normal )

**My whole JSG config (as .zip)**

[jsg.zip](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/13258930/jsg.zip)

if you need more information; please let me know and ill try to reach back when I can

**Comment by MR-Spagetty** [comment]
i have reproduced this without the presence of craft tweaker when the option is set to false the gates are still unbreakable thus cannot be mined with a pickaxe

**Comment by MR-Spagetty** [comment]
i thiml i may have found the culprit @MineDragonCZ there is no else to this if: https://github.com/Tau-ri-Dev/JSGMod-1.12.2/blob/master/src/main/java/tauri/dev/jsg/block/TechnicalBlock.java#L70C7-L70C7

**Comment by Shibva** [comment]
Thanks, hope this gets out soon
