### ISSUE TITLE
Bug:  Game Crash after trying to use admin panel once MW gate opened

### ISSUE THREAD

**Issue by mMONTAGEe** [Tau-ri-Dev/JSGMod-1.12.2#285]
**Describe the bug**
Game crashed while attempting to open admin panel during unstable wormhole stage of MW stargate connection while pointing to event horizon

**To Reproduce**
1. Dial the MW gate (in my case i was dialing planet ceres from galacticraft)
2. once gate opens, during unstable wormhole i pressed right click to open admin panel while pointing to event horizon
3. crash

**Expected behavior**
Admin panel to open so that i could disconnect gate and check other addon's new PoI's

**Screenshots**
None

**Mod version**
jsg-1.12.2-4.11.2.0-client

**Additional context**
Was using Addon for more MW PoI's in my case was selected Tokra1

**My whole JSG config (as .zip)**
https://cdn.discordapp.com/attachments/1096720092374499338/1170735468812439572/jsg.zip?ex=655a1f5e&is=6547aa5e&hm=a86b14b8de3d117eb2bc6e467a30557d1495e014cbcfee472dfae672166db6c8&

**Crash Log**
https://cdn.discordapp.com/attachments/1096720092374499338/1170736119952982046/message.txt?ex=655a1ffa&is=6547aafa&hm=2f4d3fa01e0f122360131e1f86a40d3fd6f97d8ca0619adcde2e31c7ec7db0fd&

**Comment by mMONTAGEe** [comment]
Note: i was standing very close to the gate while pointing to event horizon

**Comment by MineDragonCZ** [comment]
Have you restarted game after you loaded new point of roigins to the game?

**Comment by mMONTAGEe** [comment]
Issue was resolved, idk how

**Comment by MineDragonCZ** [comment]
> Issue was resolved, idk how

because you restared the game lol
