### ISSUE TITLE
Bug: Stupido GDO 

### ISSUE THREAD

**Issue by HDL34** [Tau-ri-Dev/JSGMod-1.12.2#286]
**Describe the bug**
After updating the mod to the latest version, the iris opening codes have disappeared. I put them back but they don't work anymore..

**To Reproduce**
1. Go to the stargate. In the Iris section of the menu, add a code and leave in automatic. Then dial the sequence from another door. 
2. Right-click on the GDO and try entering the code placed in the other gate.
3. Validate with "ok".
4. See "Wrong code" at bottom of screen. 

**Expected behavior**
Normally the iris should open by entering the code I've assigned to it.

**Screenshots**
View video file: https://files.catbox.moe/ppfano.mp4

**Mod version**
Latest version. 4.11.2.1

**Additional context**

**My whole JSG config (as .zip)**
Upload here your jsg config folder (as .zip) **if it's not default one**
[jsg.zip](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/13260380/jsg.zip)

**Comment by MR-Spagetty** [comment]
I have successfully reproduced this and found that in addition component.stargate.sendIrisCode() in the OC integration does not appear to be working correctly either, when supplied with a code it gives the following error message:
![image](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/assets/54694556/4fd9a1c1-4b49-48d4-8da0-3b80b1720855)

**Comment by HDL34** [comment]
This is a good thing. It's not an isolated bug for one machine. I'm not the only one to have it.
