### ISSUE TITLE
Bug: zpms not spawning (mod issue with biomes o plenty)

### ISSUE THREAD

**Issue by Evil2056** [Tau-ri-Dev/JSGMod-1.12.2#288]
I play on a server with a few mods but I did offline testing and determined that biomes o plenty seems to greatly affect the spawn on zpms. I was able to find a zpm in 30min without it installed and when I did the same test with is I couldn't after an hour.

**Comment by MR-Spagetty** [comment]
BOP is known to cause issues with the spawning of structures

**Comment by Fredyman95** [comment]
Structures - ancient totems are spawned on vanilla grass or vanilla sand blocks.

These blocks also can't be blocked by other structures or trees.
