### ISSUE TITLE
Bug: [uncomfirmed] unable to find any sus page to center island

### ISSUE THREAD

**Issue by Shibva** [Tau-ri-Dev/JSGMod-1.12.2#289]
**Describe the bug**
should be able to be self-explanitory when looking though stronghold chests

**To Reproduce**
Just look around stronghold generation

**Mod version**
4.11.2.3

**Additional context**

if you guys are having trouble generating something like this, then why not guarantee it by having a universe address page fly out of an end portal when you ignite it if EndTravel portal config is set to true to disable the end portals? the Adress will be linked to the center of the end islands

also you could have the end exit be usable maybe, but to encourage the use of stargates you could have it either break after being used once or have it have a 85% chance to kill you once you emerge from the otherside (due to unstable portal shit or whatnot)

**My whole JSG config (as .zip)**
Upload here your jsg config folder (as .zip) **if it's not default one**

**Comment by Fredyman95** [comment]
You must find that page in stronghold...

**Comment by Shibva** [comment]
I am aware of this; it says that it's guaranteed; however I have yet to find even one

**Comment by MineDragonCZ** [comment]
In stonghold its not classic page, its blank page, so it looks simillar to normal paper. You must click with that page to get the address.

**Comment by Shibva** [comment]
I don't have any idea what you mean; I've kept on only finding just normal paper in the two strongholds I've checked and I am aware that I need to right click to use mysterious pages


If there's supposed to be an item called a sus page and it's not a mysterious page (universe) item names that then I don't see it in JEI

Tbh im just as confused

**Comment by Fredyman95** [comment]
Sus page cant be get because sus page is variant of notebook page.

Also its a loot :D if you are in creative you can use admin controller becuase you have control which dimension you will generate (+ which gate you will generate...) also admin controler allow you to get address, tp to get... basicly its admin tool for server admins to maintenance stargates...

About stronghold loot you must be extremly unlucky or blind... becuase sus page looks exactly as paper..  but we will fix it soon with some overlay.

**Comment by MineDragonCZ** [comment]
Sus page: 
![image](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/assets/78699120/9862e681-81e9-4442-9094-d91dd80addc6)
Stronghold (End) page:
![image](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/assets/78699120/5055518f-ddbd-499d-a6b5-ad69eff461ca)
