### ISSUE TITLE
Stargates generated with 3rd-party mod aren't woring properly

### ISSUE THREAD

**Issue by matousss** [Tau-ri-Dev/JSGMod-1.12.2#42]
Another day, another bug...
Some shit with tile entities

┆Issue is synchronized with this [Trello card](https://trello.com/c/hjWeYFta) by [Unito](https://www.unito.io)

**Comment by Lloydplays** [comment]
What mod are you using I want to have that mod my pack

**Comment by MineDragonCZ** [comment]
I can not reproduce it
