### ISSUE TITLE
Some entities are not allowed to pass through a gate

### ISSUE THREAD

**Issue by Sparcky4860** [Tau-ri-Dev/JSGMod-1.12.2#91]
[broken car does not go through star gate 😕](https://youtu.be/AllX-T4oqMo)

┆Issue is synchronized with this [Trello card](https://trello.com/c/YfFdRuou) by [Unito](https://www.unito.io)

**Comment by Lloydplays** [comment]
Update through testing I found that the vehicles will now go through, but they will not show up on the other side of the gate

**Comment by MineDragonCZ** [comment]
Is the problem still here in the newest version of the mod?

**Comment by Sparcky4860** [comment]
I will test it even if I'm not an official test anymore

**Comment by MineDragonCZ** [comment]
> I will test it even if I'm not an official test anymore

It doesn't metter if u r a tester or not, you oppened a issue :)

Anyway... Got anything?

**Comment by MineDragonCZ** [comment]
Inactive
